### ISSUE TITLE
Shaperglot is incompatible with `vharfbuzz` v0.3

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/shaperglot#41]
...but it pulls it in when you install it. This results in a error trying to run shaperglot:

```
AttributeError: 'Vharfbuzz' object has no attribute 'ttfont'. Did you mean: 'hbfont'?
```

The quick fix would be to constrain vharfbuzz to <0.3 in pyproject.toml

The proper fix would be to update shaperglot to work with 0.3.0, and then update the requirement to ^0.3
